- type: job
  id: SecurityOfficer
  name: job-name-security
  description: job-description-security
  playTimeTracker: JobSecurityOfficer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 2.5h
  startingGear: SecurityOfficerGear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: SecurityOfficerGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetSecurity
    #pocket1: WeaponPistolMk58 - ES Change removes roundstart gun, replaces it with taser
    pocket1: ESWeaponHybridTaser
  storage:
    back:
    - Flash
    #- MagazinePistol - ES Change removes roundstart gun

- type: chameleonOutfit
  id: SecurityOfficerChameleonOutfit
  job: SecurityOfficer
  hasMindShield: true
  equipment:
# ES Start
    head: ClothingHeadHelmetBasic
# ES End
    mask: ClothingMaskGasSecurity
    gloves: ClothingHandsGlovesColorBlack
