- type: job
  id: Warden
  name: job-name-warden
  description: job-description-warden
  playTimeTracker: JobWarden
  requirements:
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 5h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 10h
  weight: 5
  startingGear: WardenGear
  icon: "JobIconWarden"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Armory
  - Maintenance
  - External
  - Detective
  - Cryogenics
  - GenpopEnter
  - GenpopLeave
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: WardenGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: WardenPDA
    ears: ClothingHeadsetSecurity
    #pocket1: WeaponPistolMk58 - ES Change removes roundstart gun, replaces it with taser
    pocket1: ESWeaponHybridTaser
  storage:
    back:
    - Flash
    #- MagazinePistol - ES Change removes roundstart gun, replaces it with taser

- type: chameleonOutfit
  id: WardenChameleonOutfit
  job: Warden
  hasMindShield: true
  equipment:
    head: ClothingHeadHatWarden
    mask: ClothingMaskGasSecurity
    outerClothing: ClothingOuterCoatWarden
    jumpsuit: ClothingUniformJumpsuitWarden
    neck: Dinkystar
    belt: ClothingBeltSecurity
    gloves: ClothingHandsGlovesColorBlack
    shoes: ClothingShoesBootsJack
